### ISSUE TITLE
Problemi con il Bearer Token

### ISSUE THREAD

**Issue by Giasinit** [sim-pez/ridemovi-bike#1]
Ciao!
Come faccio ad avere il mio token Bearer per poter vedere la lista dei mezzi?

thx

**Comment by sim-pez** [comment]
Purtroppo va richiesto a Ridemovi ma non so se lo forniscono a privati

**Comment by Giasinit** [comment]
però bro.. a me sembri strano però eh

**Comment by Giasinit** [comment]
Non so se sei a conoscenza di RideGodi.. una sorta di hack fatto per ridedott.. proprio inizio di giugno 2024.. e tu che fai sta cosa subito dopo.. sei sospetto ahaha

**Comment by sim-pez** [comment]
Lavoro nel settore

**Comment by Giasinit** [comment]
ci sta ci sta.. comunque daje.. ti ringrazio del codice :)
